#
#	This file is part of the OrangeFox Recovery Project
# 	Copyright (C) 2023 The OrangeFox Recovery Project
#

# OrangeFox settings
OF_QUICK_BACKUP_LIST := /boot;/data;/dtbo;
OF_SKIP_MULTIUSER_FOLDERS_BACKUP := 1
OF_ENABLE_USB_STORAGE := 1
OF_IGNORE_LOGICAL_MOUNT_ERRORS := 1
OF_BIND_MOUNT_SDCARD_ON_FORMAT := 1
OF_FORCE_CASEFOLDING := 1
OF_AB_DEVICE_WITH_RECOVERY_PARTITION := 0
OF_NO_TREBLE_COMPATIBILITY_CHECK := 1
OF_FBE_METADATA_MOUNT_IGNORE="1"

# OrangeFox GUI settings
OF_USE_GREEN_LED := 0
OF_FLASHLIGHT_ENABLE := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_SCREEN_H := 2400
OF_STATUS_H := 100
OF_STATUS_INDENT_LEFT := 48
OF_STATUS_INDENT_RIGHT := 48
OF_HIDE_NOTCH := 0
OF_CLOCK_POS := 1
OF_OPTIONS_LIST_NUM := 6

# Recovery additional features	
OF_ENABLE_LPTOOLS := 1
OF_RECOVERY_AB_FULL_REFLASH_RAMDISK := 1
OF_DISABLE_OTA_MENU := 0
OF_DYNAMIC_FULL_SIZE := 11425243136

# OTA (Modified for custom ROMs & Decryption)
OF_KEEP_DM_VERITY_FORCED_ENCRYPTION := 1
OF_KEEP_DM_VERITY := 0
OF_SUPPORT_ALL_BLOCK_OTA_UPDATES := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1

# f2fs compression
OF_ENABLE_FS_COMPRESSION := 1

# try to prevent potential data format errors
OF_UNBIND_SDCARD_F2FS := 1

# avb 2.0
OF_PATCH_AVB20 := 1

#Autor
OF_MAINTAINER := "Miranda_OFRP"

# Maximun permissible splash image size (in kilobytes); do "NOT" increase
OF_SPLASH_MAX_SIZE := "130"
